apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: personal-app-route
  namespace: default # Change this if your app is in a different namespace
spec:
  entryPoints:
    - web # This corresponds to the web entry point you set up on Port 80
  routes:
    - match: PathPrefix(`/`) # Change this to the domain you will use
      kind: Rule
      services:
        - name: personal-app-service # Must be the name of your Kubernetes Service
          port: 80            # Must be the target port of that Service/PodsapiVersion: traefik.io/v1alpha1
